### PR TITLE
Fix a ton of shit

### PR DESCRIPTION
**Pull request by thebigsmileXD**
if you go back 1 commit on your repo, everything will work.

### CODE REVIEW

**Comment by Driesboy** [comment]
WOW thx

**Comment by Driesboy** [comment]
+1

**Comment by Driesboy** [comment]
+1

**Comment by thebigsmileXD** [comment]
I was just pissed seing such a mess

**Comment by thebigsmileXD** [comment]
.. you didn't revert your latest commit as i stated above. GG nicely broken the plugin again

**Comment by Driesboy** [comment]
nope the plugin works btw

**Comment by Driesboy** [comment]
but poggit is hanging

**Comment by thebigsmileXD** [comment]
Sure its hanging, because it caused issues, as i stated

**Comment by Driesboy** [comment]
can you fix it???

Op 2-mei-2017 08:06 schreef "XenialDan" <notifications@github.com>:

**Comment by thebigsmileXD** [comment]
revert the merge, revert another commit, then pullaprove

**Comment by Driesboy** [comment]
ok

Op 2-mei-2017 08:11 schreef "XenialDan" <notifications@github.com>:

**Comment by Driesboy** [comment]
idk how to do that

**Comment by Driesboy** [comment]
can you open a new one??

**Comment by thebigsmileXD** [comment]
There isn’t anything to compare.
NL-4-DEVS:master is up to date with all commits from thebigsmileXD:master. Try switching the base for your comparison.

**Comment by Driesboy** [comment]
if i give you owner of this repo can you fix it than??

**Pull request merged**
